import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="keywords"
          content="nextjs, huntingCoder blog, hunting coder"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <img
            className={styles.myImg}
            src="/hpm.jpg"
            alt="hunting coder"
            width={237}
            height={158}
          />
        </div>
        <h1 className={styles.title}>
          <span className="dummy">HuntingCoder</span>
        </h1>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2024?</h3>
            <p>
              Start by mastering the fundamentals – variables, loops, and
              functions. Practice through small projects and explore the DOM.
              Dive into asynchronous programming and gain a deep understanding
              of ES6+ features for modern development.
            </p>
            <Link href="/blog">
              <button className={styles.btn}>Read More</button>
            </Link>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn Typescript in 2024?</h3>
            <p className={styles.p}>
              Transition seamlessly from JavaScript by introducing static
              typing. Learn TypeScript syntax, interfaces, and generics.
              Leverage TypeScript's robust tooling for better code maintenance.
              Practice converting existing JavaScript projects to TypeScript for
              hands-on experience.
            </p>
            <Link href="/blog">
              <button className={styles.btn}>Read More</button>
            </Link>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn React in 2024?</h3>
            <p>
              Begin with React basics, JSX, and components. Grasp state
              management and component lifecycles. Explore React Router for
              navigation and integrate with external APIs. Advance to stateful
              management with Redux or Context API. Build and deploy projects to
              solidify your React skills.
            </p>
            <Link href="/blog">
              <button className={styles.btn}>Read More</button>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
